services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: "1353"
      POSTGRES_DB: fastapi
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:/var/lib/postgresql/data